### ISSUE TITLE
[SOLVED] Command /cprivate or /cpublic doens't work

### ISSUE THREAD

**Issue by akiraic** [dmulloy2/LWC#11]
Using those commands gives you the output "Please left click your block to lock it", but when left clicking the block, it does nothing. Neither commands or using /lwc mode persist before.
Permissions are ok: 1 user, 1 group with plugin.* from all plugins in the server, including LWC, who is also OP.
Video of the said situation: https://youtu.be/yfWf7baS31c
Using: Latest version of LWC (dev 10).

Also, command /cinfo seens to be working fine, and blocks listed to be protected automatically are also working fine.

**Comment by RoyCurtis** [comment]
In your video, you are attempting to lock a glowstone block, mossy cobblestone fence and pink wool. However, by default, [LWC is not configured to lock these blocks](https://github.com/dmulloy2/LWC/blob/master/core/src/main/resources/config/core.yml#L167).

To fix this, [try adding the following to your `core.yml` under the `blocks` section](http://i.imgur.com/iowz8C0.png), then do `/lwc admin reload`:

```yaml
        glowstone:
            enabled: true
        # Mossy cobblestone wall
        '139:1':
            enabled: true
        # Pink wool
        '35:6':
            enabled: true
```

If you want to make _everything_ lockable (I wouldn't recommend this, personally), you could use the wildcard feature that this fork provides, by adding this to the `blocks` section:

```yaml
        # Everything
        '*':
            enabled: true
```
