### ISSUE TITLE
LWC::Event: c.g.l.LWCPlayerListener (PlayerInteractEvent) causing high tick lag and lag spikes.

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#22]
LWC dev 18 on a fresh new database with less than 1k protections.

I was getting some random lag spikes occasionally so I ran a timings report. LWC is reported as being near the top of causing the problem. Is there any micro-optimizing that can be done to the interact listener?

Timings report.
https://timings.aikar.co/?id=cd10e2beb4784d9d9f47017650008ab5

```
core:
    locale: en
    flushInterval: 10
    cacheSize: 30000
    precache: -1
    showNotices: true
    showMyNotices: false
    opIsLWCAdmin: true
    disableHistory: true
    townyBorders: false
    groupPrefix: group.
    updateNotifier: false
optional:
    onlyProtectWhenOwnerIsOnline: false
    onlyProtectWhenOwnerIsOffline: false
    exemptBlocks: []
    optOut: true
    blacklistedBlocks:
    - 166
    - 154
    blacklistedPlayers:
    - plr
    useProtectionLimits: true
    fastHopperProtection: true
database:
    adapter: mysql
    path: plugins/LWC/lwc.db
    host: localhost
    database: 
    username: 
    password: 
    prefix: 
    ping_interval: 300
protections:
    denyRedstone: false
    denyHoppers: true
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    ignoreExplosions: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    quiet: false
    readonly-modify: false
    readonly-remove: false
    blocks:
        chest:
            enabled: true
        trapped_chest:
            enabled: true
        furnace:
            enabled: true
        dispenser:
            enabled: true
        wooden_door:
            enabled: true
        iron_door:
            enabled: true
        spruce_door:
            enabled: true
        birch_door:
            enabled: true
        jungle_door:
            enabled: true
        acacia_door:
            enabled: true
        dark_oak_door:
            enabled: true
        trap_door:
            enabled: true
        iron_trapdoor:
            enabled: true
        fence_gate:
            enabled: true
        spruce_fence_gate:
            enabled: true
        birch_fence_gate:
            enabled: true
        jungle_fence_gate:
            enabled: true
        acacia_fence_gate:
            enabled: true
        dark_oak_fence_gate:
            enabled: true
        standing_banner:
            enabled: true
        wall_banner:
            enabled: true
        white_shulker_box:
            enabled: true
        orange_shulker_box:
            enabled: true
        magenta_shulker_box:
            enabled: true
        light_blue_shulker_box:
            enabled: true
        yellow_shulker_box:
            enabled: true
        lime_shulker_box:
            enabled: true
        pink_shulker_box:
            enabled: true
        gray_shulker_box:
            enabled: true
        silver_shulker_box:
            enabled: true
        cyan_shulker_box:
            enabled: true
        purple_shulker_box:
            enabled: true
        blue_shulker_box:
            enabled: true
        brown_shulker_box:
            enabled: true
        green_shulker_box:
            enabled: true
        red_shulker_box:
            enabled: true
        black_shulker_box:
            enabled: true
modes:
    droptransfer:
        enabled: false
        crossWorld: false
    persist:
        enabled: true
```
